import type { Race } from './types';

const V = '2026-08-22';

/** 국내 대회. flight_hours 는 서울 기준 편도 이동 소요시간(시간). */
export const RACES_KR: Race[] = [
  {
    id: 'cheorwon-dmz',
    name_ko: '철원 DMZ 국제평화마라톤',
    name_en: 'Cheorwon DMZ International Peace Marathon',
    city_ko: '강원 철원',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-09-05',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-06-01',
    entry_closes: '2026-08-14',
    entry_confidence: 'expected',
    entry_fee: 40000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km', '5km'],
    field_size: 8000,
    course: '완만',
    flight_hours: 2.0,
    official_url: 'https://www.cwdmzmarathon.com/',
    source_url: 'https://www.ahotu.com/calendar/running/marathon/south-korea',
    last_verified: V,
    notes_ko: '민통선 안쪽을 달리는 구간이 있어 신분증 지참 필수.',
  },
  {
    id: 'geumsan',
    name_ko: '금산인삼축제 마라톤',
    name_en: 'Geumsan Ginseng Festival Marathon',
    city_ko: '충남 금산',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-09-19',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-01',
    entry_closes: '2026-09-04',
    entry_confidence: 'expected',
    entry_fee: 35000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km', '5km'],
    field_size: 5000,
    course: '완만',
    flight_hours: 2.5,
    official_url: 'https://www.geumsan.go.kr/',
    source_url: 'https://www.ahotu.com/calendar/running/marathon/south-korea',
    last_verified: V,
    notes_ko: '인삼축제 기간과 겹쳐 대회 후 축제 구경을 겸할 수 있다.',
  },
  {
    id: 'gongju',
    name_ko: '공주 백제마라톤',
    name_en: 'Gongju Baekje Marathon',
    city_ko: '충남 공주',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-09-20',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-01',
    entry_closes: '2026-09-04',
    entry_confidence: 'expected',
    entry_fee: 45000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '32km', '하프', '10km', '5km'],
    field_size: 7000,
    course: '완만',
    flight_hours: 2.0,
    official_url: 'https://www.gongjumarathon.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: '가을 풀코스 시즌 첫 대회로 춘천·JTBC 대비 훈련 삼아 뛰는 경우가 많다. 32km 종목이 따로 있다.',
  },
  {
    id: 'andong',
    name_ko: '안동마라톤',
    name_en: 'Andong Marathon',
    city_ko: '경북 안동',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-10-04',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-15',
    entry_closes: '2026-09-18',
    entry_confidence: 'expected',
    entry_fee: 40000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km', '5km'],
    field_size: 5000,
    course: '완만',
    flight_hours: 3.0,
    official_url: 'https://www.andong.go.kr/',
    source_url: 'https://www.ahotu.com/calendar/running/marathon/south-korea',
    last_verified: V,
    notes_ko: null,
  },
  {
    id: 'gangnam-peace',
    name_ko: '강남 국제평화마라톤',
    name_en: 'Gangnam International Peace Marathon',
    city_ko: '서울 강남',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-10-05',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-20',
    entry_closes: '2026-09-20',
    entry_confidence: 'expected',
    entry_fee: 40000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km', '5km'],
    field_size: 10000,
    course: '평지',
    flight_hours: 0.5,
    official_url: 'https://www.gangnam.go.kr/',
    source_url: 'https://www.ahotu.com/calendar/running/marathon/south-korea',
    last_verified: V,
    notes_ko: '서울 도심 대회라 이동 부담이 거의 없다.',
  },
  {
    id: 'naju',
    name_ko: 'MBN 나주마라톤',
    name_en: 'MBN Naju National Marathon',
    city_ko: '전남 나주',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-10-11',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-20',
    entry_closes: '2026-09-25',
    entry_confidence: 'expected',
    entry_fee: 45000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '하프', '10km', '5km'],
    field_size: 6000,
    course: '평지',
    flight_hours: 3.5,
    official_url: 'https://www.najumarathon.com/',
    source_url: 'https://www.ahotu.com/calendar/running/marathon/south-korea',
    last_verified: V,
    notes_ko: null,
  },
  {
    id: 'gyeongju-intl',
    name_ko: '경주국제마라톤',
    name_en: 'Gyeongju International Marathon',
    city_ko: '경북 경주',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-10-17',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-01',
    entry_closes: '2026-09-25',
    entry_confidence: 'expected',
    entry_fee: 60000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '하프', '10km'],
    field_size: 12000,
    course: '완만',
    flight_hours: 3.0,
    official_url: 'https://www.gyeongjumarathon.com/',
    source_url: 'https://wooyupost.com/2026-%EA%B2%BD%EC%A3%BC%EA%B5%AD%EC%A0%9C%EB%A7%88%EB%9D%BC%ED%86%A4-%EC%A0%91%EC%88%98-%EC%8B%A0%EC%B2%AD-%EB%B0%A9%EB%B2%95-%EC%BD%94%EC%8A%A4-%EC%9D%BC%EC%A0%95/',
    last_verified: V,
    notes_ko: '보문단지 일대를 도는 가을 대표 대회. 코스가 예쁘고 기록도 잘 나온다는 평이 많다.',
  },
  {
    id: 'daecheongho',
    name_ko: '청원생명쌀 대청호마라톤',
    name_en: 'Cheongwon Daecheong Lake Marathon',
    city_ko: '충북 청주',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-10-17',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-20',
    entry_closes: '2026-09-30',
    entry_confidence: 'expected',
    entry_fee: 40000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '하프', '10km', '5km'],
    field_size: 6000,
    course: '언덕',
    flight_hours: 1.5,
    official_url: 'https://www.dcmarathon.co.kr/',
    source_url: 'https://www.ahotu.com/calendar/running/marathon/south-korea',
    last_verified: V,
    notes_ko: '호수를 끼고 도는 코스라 경치는 좋지만 오르내림이 꾸준히 있다.',
  },
  {
    id: 'chuncheon',
    name_ko: '춘천마라톤',
    name_en: 'Chuncheon International Marathon',
    city_ko: '강원 춘천',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-10-25',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-14',
    entry_closes: '2026-07-14',
    entry_confidence: 'confirmed',
    entry_fee: 150000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '10km'],
    field_size: 20000,
    course: '언덕',
    flight_hours: 1.5,
    official_url: 'https://www.chuncheonmarathon.com/',
    source_url: 'https://blog.sharetoctoc.com/chuncheon-marathon-registration-schedule/',
    last_verified: V,
    notes_ko: '국내 최고 인기 대회. 선착순이라 오픈 당일 분 단위로 마감된다. 의암호 코스는 후반 오르막이 있다.',
  },
  {
    id: 'jtbc-seoul',
    name_ko: 'JTBC 서울마라톤',
    name_en: 'JTBC Seoul Marathon',
    city_ko: '서울',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2026-11-01',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-07-28',
    entry_closes: '2026-08-11',
    entry_confidence: 'expected',
    entry_fee: 150000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '10km'],
    field_size: 35000,
    course: '평지',
    flight_hours: 0.5,
    official_url: 'https://www.jtbcmarathon.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: '상암 출발 잠실 도착. 국내 최대 규모이고 평지라 기록 도전용으로 많이 선택한다. 10km 는 10만원.',
  },
  {
    id: 'daegu',
    name_ko: '대구국제마라톤',
    name_en: 'Daegu International Marathon',
    city_ko: '대구',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2027-02-21',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-11-01',
    entry_closes: '2027-01-15',
    entry_confidence: 'expected',
    entry_fee: 50000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '10.9km', '건강달리기'],
    field_size: 20000,
    course: '평지',
    flight_hours: 2.0,
    official_url: 'https://www.daegumarathon.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: '월드 애슬레틱스 골드 라벨. 2월이라 기온이 낮아 기록이 잘 나온다.',
  },
  {
    id: 'seoul-marathon',
    name_ko: '서울마라톤 (동아마라톤)',
    name_en: 'Seoul Marathon',
    city_ko: '서울',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2027-03-14',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-06-01',
    entry_closes: '2026-06-02',
    entry_confidence: 'expected',
    entry_fee: 100000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '10km'],
    field_size: 38000,
    course: '평지',
    flight_hours: 0.5,
    official_url: 'https://seoul-marathon.com/',
    source_url: 'https://runningwikii.com/entry/seoul-marathon-2027-registration-schedule/',
    last_verified: V,
    notes_ko: '국내 유일 월드 애슬레틱스 플래티넘 라벨. 기록 제출 → 우선접수 → 그룹별 본접수 순서라 일정 관리가 필요하다. 골드패키지는 40만원.',
  },
  {
    id: 'incheon-half',
    name_ko: '인천국제하프마라톤',
    name_en: 'Incheon International Half Marathon',
    city_ko: '인천',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2027-03-21',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2027-01-05',
    entry_closes: '2027-02-20',
    entry_confidence: 'expected',
    entry_fee: 48000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km', '5km'],
    field_size: 12000,
    course: '평지',
    flight_hours: 1.0,
    official_url: 'https://www.incheonmarathon.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: null,
  },
  {
    id: 'gyeongju-cherry',
    name_ko: '경주 벚꽃마라톤',
    name_en: 'Gyeongju Cherry Blossom Marathon',
    city_ko: '경북 경주',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2027-04-03',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2027-01-10',
    entry_closes: '2027-03-10',
    entry_confidence: 'expected',
    entry_fee: 50000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km', '5km'],
    field_size: 15000,
    course: '완만',
    flight_hours: 3.0,
    official_url: 'https://www.gjcbmarathon.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: '벚꽃 시즌과 겹쳐 조기 마감된다. 숙소도 미리 잡아야 한다.',
  },
  {
    id: 'dmz-peace',
    name_ko: 'DMZ 평화마라톤',
    name_en: 'DMZ Peace Marathon',
    city_ko: '경기 임진각',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2027-04-18',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2027-01-20',
    entry_closes: '2027-03-25',
    entry_confidence: 'expected',
    entry_fee: 45000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km', '5km'],
    field_size: 10000,
    course: '완만',
    flight_hours: 1.5,
    official_url: 'https://www.dmzmarathon.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: '임진각 출발. 신분 확인 절차가 있어 여유 있게 도착해야 한다.',
  },
  {
    id: 'seoul-half',
    name_ko: '서울하프마라톤 (조선일보)',
    name_en: 'Seoul Half Marathon',
    city_ko: '서울',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2027-04-25',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2027-02-01',
    entry_closes: '2027-03-20',
    entry_confidence: 'expected',
    entry_fee: 55000,
    entry_fee_currency: 'KRW',
    distances: ['하프', '10km'],
    field_size: 20000,
    course: '평지',
    flight_hours: 0.5,
    official_url: 'https://www.seoulhalf.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: '광화문 출발. 하프 입문용으로 가장 많이 추천되는 대회.',
  },
  {
    id: 'jeju',
    name_ko: '제주국제마라톤',
    name_en: 'Jeju International Marathon',
    city_ko: '제주',
    country_ko: '대한민국',
    country_code: 'KR',
    region: '한국',
    race_date: '2027-04-25',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2027-01-15',
    entry_closes: '2027-04-01',
    entry_confidence: 'expected',
    entry_fee: 50000,
    entry_fee_currency: 'KRW',
    distances: ['풀', '하프', '10km'],
    field_size: 8000,
    course: '완만',
    flight_hours: 1.2,
    official_url: 'https://www.jejumarathon.com/',
    source_url: 'https://dategom.com/2026-%EC%A0%84%EA%B5%AD-%EB%A7%88%EB%9D%BC%ED%86%A4%EB%8C%80%ED%9A%8C-%EC%9D%BC%EC%A0%95-%EC%9B%94%EB%B3%84-%EC%A0%95%EB%A6%AC/',
    last_verified: V,
    notes_ko: '국내 대회지만 항공·숙박이 붙어 사실상 여행이 된다. 4월 제주는 바람이 변수.',
  },
];
