import type { Race } from './types';

const V = '2026-08-22';
const SRC = 'https://marathonscout.com/marathon-calendar';

/** 2차로 추가한 해외 대회. */
export const RACES_MORE: Race[] = [
  // ── 일본 ──
  {
    id: 'kanazawa', name_ko: '가나자와 마라톤', name_en: 'Kanazawa Marathon',
    city_ko: '가나자와', country_ko: '일본', country_code: 'JP', region: '일본',
    race_date: '2026-10-25', date_confidence: 'confirmed', is_major: false,
    entry_type: 'lottery', entry_opens: '2026-04-01', entry_closes: '2026-05-15', entry_confidence: 'expected',
    entry_fee: 15000, entry_fee_currency: 'JPY', distances: ['풀'], field_size: 13000,
    course: '평지', flight_hours: 2.5,
    official_url: 'https://www.kanazawa-marathon.jp/', source_url: SRC, last_verified: V,
    notes_ko: '호쿠리쿠 대표 대회. 도쿄·오사카보다 경쟁률이 낮아 당첨 확률이 높은 편.',
  },
  {
    id: 'fukuoka', name_ko: '후쿠오카 마라톤', name_en: 'Fukuoka Marathon',
    city_ko: '후쿠오카', country_ko: '일본', country_code: 'JP', region: '일본',
    race_date: '2026-11-08', date_confidence: 'confirmed', is_major: false,
    entry_type: 'lottery', entry_opens: '2026-04-01', entry_closes: '2026-05-08', entry_confidence: 'expected',
    entry_fee: 14000, entry_fee_currency: 'JPY', distances: ['풀', '5.2km'], field_size: 12000,
    course: '평지', flight_hours: 1.5,
    official_url: 'https://www.f-marathon.jp/', source_url: 'https://www.finishers.com/en/event/fukuoka-marathon', last_verified: V,
    notes_ko: '인천에서 1시간 30분. 해안선을 따라 달리는 평지 코스로 한국에서 가장 가기 쉬운 일본 풀코스.',
  },
  {
    id: 'hofu', name_ko: '호후 요미우리 마라톤', name_en: 'Hofu Yomiuri Marathon',
    city_ko: '야마구치 호후', country_ko: '일본', country_code: 'JP', region: '일본',
    race_date: '2026-12-06', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-08-01', entry_closes: '2026-10-10', entry_confidence: 'expected',
    entry_fee: 11000, entry_fee_currency: 'JPY', distances: ['풀'], field_size: 10000,
    course: '평지', flight_hours: 2.0,
    official_url: 'https://hofu-yomiuri-marathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '기록 도전자들이 모이는 대회. 제한시간이 4시간으로 짧은 편이라 주의.',
  },
  {
    id: 'hokkaido', name_ko: '홋카이도 마라톤', name_en: 'Hokkaido Marathon',
    city_ko: '삿포로', country_ko: '일본', country_code: 'JP', region: '일본',
    race_date: '2027-08-29', date_confidence: 'expected', is_major: false,
    entry_type: 'lottery', entry_opens: '2027-03-20', entry_closes: '2027-04-20', entry_confidence: 'expected',
    entry_fee: 16500, entry_fee_currency: 'JPY', distances: ['풀'], field_size: 20000,
    course: '평지', flight_hours: 3.0,
    official_url: 'https://hokkaido-marathon.com/', source_url: 'https://japan-event.info/en/articles/japan-marathons-guide', last_verified: V,
    notes_ko: '일본에서 드문 한여름 대회. 더위 대비가 필수지만 삿포로 도심을 달린다.',
  },

  // ── 아시아 ──
  {
    id: 'kualalumpur', name_ko: '쿠알라룸푸르 마라톤', name_en: 'Standard Chartered KL Marathon',
    city_ko: '쿠알라룸푸르', country_ko: '말레이시아', country_code: 'MY', region: '아시아',
    race_date: '2026-10-04', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-04-01', entry_closes: '2026-09-10', entry_confidence: 'expected',
    entry_fee: 230, entry_fee_currency: 'MYR', distances: ['풀', '하프', '10km', '5km'], field_size: 40000,
    course: '완만', flight_hours: 6.5,
    official_url: 'https://www.kl-marathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '새벽 출발이지만 습도가 높다. 물가가 싸서 총비용은 아시아 대회 중 낮은 편.',
  },
  {
    id: 'jakarta', name_ko: '자카르타 러닝 페스티벌 마라톤', name_en: 'Jakarta Running Festival Marathon',
    city_ko: '자카르타', country_ko: '인도네시아', country_code: 'ID', region: '아시아',
    race_date: '2026-10-25', date_confidence: 'expected', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-05-01', entry_closes: '2026-09-30', entry_confidence: 'expected',
    entry_fee: 850000, entry_fee_currency: 'IDR', distances: ['풀', '하프', '10km'], field_size: 20000,
    course: '평지', flight_hours: 7.0,
    official_url: 'https://jakartarunningfestival.com/', source_url: SRC, last_verified: V,
    notes_ko: null,
  },
  {
    id: 'hochiminh', name_ko: '호치민 마라톤', name_en: 'Techcombank Ho Chi Minh City Marathon',
    city_ko: '호치민', country_ko: '베트남', country_code: 'VN', region: '아시아',
    race_date: '2026-12-06', date_confidence: 'expected', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-06-01', entry_closes: '2026-11-15', entry_confidence: 'expected',
    entry_fee: 1500000, entry_fee_currency: 'VND', distances: ['풀', '하프', '10km', '5km'], field_size: 15000,
    course: '평지', flight_hours: 5.5,
    official_url: 'https://hcmc.techcombankmarathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '새벽 3시대 출발. 항공·숙박이 저렴해 첫 해외 풀코스로 자주 언급된다.',
  },
  {
    id: 'chiangmai', name_ko: '치앙마이 마라톤', name_en: 'Chiang Mai Marathon',
    city_ko: '치앙마이', country_ko: '태국', country_code: 'TH', region: '아시아',
    race_date: '2026-12-20', date_confidence: 'expected', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-07-01', entry_closes: '2026-11-30', entry_confidence: 'expected',
    entry_fee: 1600, entry_fee_currency: 'THB', distances: ['풀', '하프', '10km'], field_size: 12000,
    course: '완만', flight_hours: 6.0,
    official_url: 'https://www.chiangmaimarathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '12월 치앙마이는 건기라 아시아 대회 중 날씨가 가장 낫다.',
  },
  {
    id: 'bangkok', name_ko: '방콕 마라톤', name_en: 'Amazing Thailand Bangkok Marathon',
    city_ko: '방콕', country_ko: '태국', country_code: 'TH', region: '아시아',
    race_date: '2027-01-10', date_confidence: 'expected', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-08-01', entry_closes: '2026-12-20', entry_confidence: 'expected',
    entry_fee: 1800, entry_fee_currency: 'THB', distances: ['풀', '하프', '10km'], field_size: 20000,
    course: '평지', flight_hours: 6.0,
    official_url: 'https://www.bkkmarathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '새벽 2시 출발. 더위를 피하려는 구성이라 수면 계획이 중요하다.',
  },

  // ── 유럽 ──
  {
    id: 'oslo', name_ko: '오슬로 마라톤', name_en: 'DNB Oslo Marathon',
    city_ko: '오슬로', country_ko: '노르웨이', country_code: 'NO', region: '유럽',
    race_date: '2026-09-12', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2025-11-01', entry_closes: '2026-09-01', entry_confidence: 'expected',
    entry_fee: 1200, entry_fee_currency: 'NOK', distances: ['풀', '하프', '10km'], field_size: 10000,
    course: '완만', flight_hours: 13.0,
    official_url: 'https://oslomaraton.no/', source_url: SRC, last_verified: V,
    notes_ko: null,
  },
  {
    id: 'cologne', name_ko: '쾰른 마라톤', name_en: 'Cologne Marathon',
    city_ko: '쾰른', country_ko: '독일', country_code: 'DE', region: '유럽',
    race_date: '2026-10-04', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2025-11-01', entry_closes: '2026-09-20', entry_confidence: 'expected',
    entry_fee: 95, entry_fee_currency: 'EUR', distances: ['풀', '하프', '10km'], field_size: 25000,
    course: '평지', flight_hours: 12.0,
    official_url: 'https://www.koeln-marathon.de/', source_url: SRC, last_verified: V,
    notes_ko: '베를린 추첨 탈락 시 같은 시즌 대안으로 자주 선택된다.',
  },
  {
    id: 'porto', name_ko: '포르투 마라톤', name_en: 'Porto Marathon',
    city_ko: '포르투', country_ko: '포르투갈', country_code: 'PT', region: '유럽',
    race_date: '2026-11-08', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-03-01', entry_closes: '2026-10-25', entry_confidence: 'expected',
    entry_fee: 60, entry_fee_currency: 'EUR', distances: ['풀', '하프'], field_size: 8000,
    course: '완만', flight_hours: 16.0,
    official_url: 'https://www.maratonadoporto.com/', source_url: SRC, last_verified: V,
    notes_ko: '참가비가 유럽에서 가장 싼 편. 도우루 강변 코스.',
  },
  {
    id: 'nice-cannes', name_ko: '니스-칸 마라톤', name_en: 'Marathon des Alpes-Maritimes Nice-Cannes',
    city_ko: '니스', country_ko: '프랑스', country_code: 'FR', region: '유럽',
    race_date: '2026-11-08', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-01-15', entry_closes: '2026-10-25', entry_confidence: 'expected',
    entry_fee: 85, entry_fee_currency: 'EUR', distances: ['풀'], field_size: 12000,
    course: '평지', flight_hours: 14.0,
    official_url: 'https://www.marathon06.com/', source_url: SRC, last_verified: V,
    notes_ko: '지중해 해안도로를 따라 니스에서 칸까지 편도로 달린다.',
  },
  {
    id: 'florence', name_ko: '피렌체 마라톤', name_en: 'Firenze Marathon',
    city_ko: '피렌체', country_ko: '이탈리아', country_code: 'IT', region: '유럽',
    race_date: '2026-11-29', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-01-10', entry_closes: '2026-11-15', entry_confidence: 'expected',
    entry_fee: 80, entry_fee_currency: 'EUR', distances: ['풀'], field_size: 10000,
    course: '평지', flight_hours: 13.0,
    official_url: 'https://www.firenzemarathon.it/', source_url: SRC, last_verified: V,
    notes_ko: '두오모 앞을 지나는 코스. 평지에 가까워 기록도 노려볼 만하다.',
  },
  {
    id: 'prague', name_ko: '프라하 마라톤', name_en: 'Prague International Marathon',
    city_ko: '프라하', country_ko: '체코', country_code: 'CZ', region: '유럽',
    race_date: '2027-05-09', date_confidence: 'expected', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-06-01', entry_closes: '2027-04-20', entry_confidence: 'expected',
    entry_fee: 3200, entry_fee_currency: 'CZK', distances: ['풀'], field_size: 10000,
    course: '평지', flight_hours: 12.0,
    official_url: 'https://www.runczech.com/', source_url: 'https://fatmarathoner.com/prague-international-marathon-guide/', last_verified: V,
    notes_ko: '구시가지 광장 출발. 돌바닥 구간이 있어 신발 선택이 중요하다.',
  },

  // ── 북미 ──
  {
    id: 'toronto', name_ko: '토론토 워터프론트 마라톤', name_en: 'TCS Toronto Waterfront Marathon',
    city_ko: '토론토', country_ko: '캐나다', country_code: 'CA', region: '북미',
    race_date: '2026-10-18', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2025-11-01', entry_closes: '2026-10-01', entry_confidence: 'expected',
    entry_fee: 165, entry_fee_currency: 'CAD', distances: ['풀', '하프', '5km'], field_size: 26000,
    course: '평지', flight_hours: 14.0,
    official_url: 'https://www.torontowaterfrontmarathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '캐나다 최대 규모. 평지 코스라 보스턴 기준기록 도전용으로 인기.',
  },
  {
    id: 'marine-corps', name_ko: '해병대 마라톤', name_en: 'Marine Corps Marathon',
    city_ko: '워싱턴 D.C.', country_ko: '미국', country_code: 'US', region: '북미',
    race_date: '2026-10-25', date_confidence: 'confirmed', is_major: false,
    entry_type: 'lottery', entry_opens: '2026-02-01', entry_closes: '2026-03-01', entry_confidence: 'expected',
    entry_fee: 235, entry_fee_currency: 'USD', distances: ['풀', '10km'], field_size: 30000,
    course: '완만', flight_hours: 14.0,
    official_url: 'https://www.marinemarathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '워싱턴 주요 기념물을 지나는 코스. 완주 메달을 해병대원이 걸어준다.',
  },
  {
    id: 'philadelphia', name_ko: '필라델피아 마라톤', name_en: 'Philadelphia Marathon',
    city_ko: '필라델피아', country_ko: '미국', country_code: 'US', region: '북미',
    race_date: '2026-11-22', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-01-15', entry_closes: '2026-11-01', entry_confidence: 'expected',
    entry_fee: 175, entry_fee_currency: 'USD', distances: ['풀', '하프', '8km'], field_size: 25000,
    course: '완만', flight_hours: 14.5,
    official_url: 'https://www.philadelphiamarathon.com/', source_url: SRC, last_verified: V,
    notes_ko: null,
  },
  {
    id: 'cim', name_ko: 'CIM 새크라멘토 마라톤', name_en: 'California International Marathon',
    city_ko: '새크라멘토', country_ko: '미국', country_code: 'US', region: '북미',
    race_date: '2026-12-06', date_confidence: 'confirmed', is_major: false,
    entry_type: 'fcfs', entry_opens: '2026-02-01', entry_closes: '2026-11-01', entry_confidence: 'expected',
    entry_fee: 190, entry_fee_currency: 'USD', distances: ['풀'], field_size: 10000,
    course: '평지', flight_hours: 11.5,
    official_url: 'https://runsra.org/california-international-marathon/', source_url: SRC, last_verified: V,
    notes_ko: '전체적으로 내리막인 코스라 미국 내 대표적인 보스턴 기준기록 도전 대회.',
  },
  {
    id: 'houston', name_ko: '휴스턴 마라톤', name_en: 'Chevron Houston Marathon',
    city_ko: '휴스턴', country_ko: '미국', country_code: 'US', region: '북미',
    race_date: '2027-01-17', date_confidence: 'expected', is_major: false,
    entry_type: 'lottery', entry_opens: '2026-05-01', entry_closes: '2026-05-20', entry_confidence: 'expected',
    entry_fee: 175, entry_fee_currency: 'USD', distances: ['풀', '하프'], field_size: 27000,
    course: '평지', flight_hours: 15.0,
    official_url: 'https://www.chevronhoustonmarathon.com/', source_url: SRC, last_verified: V,
    notes_ko: '1월 개최라 기온이 낮고 완전 평지. 기록 코스로 평이 좋다.',
  },
];
