import type { Race, Agency, Package, CostBaseline } from './types';

/**
 * 초기 시드 데이터.
 * Supabase 미설정 시 이 데이터로 동작하고, 설정 시 DB 값이 우선한다.
 * 모든 레코드는 source_url / last_verified 를 가지며, 날짜가 미확정인 건
 * date_confidence = 'expected' | 'tbc' 로 표시한다.
 */

const V = '2026-08-22';

export const RACES: Race[] = [
  // ── 일본 ──────────────────────────────────────────────
  {
    id: 'yokohama',
    name_ko: '요코하마 마라톤',
    name_en: 'Yokohama Marathon',
    city_ko: '요코하마',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2026-10-25',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-04-01',
    entry_closes: '2026-05-15',
    entry_confidence: 'expected',
    entry_fee: 18500,
    entry_fee_currency: 'JPY',
    distances: ['풀', '2km'],
    field_size: 25000,
    course: '평지',
    flight_hours: 2.5,
    official_url: 'https://yokohamamarathon.jp/',
    source_url: 'https://japan-event.info/en/articles/japan-marathons-guide',
    last_verified: V,
    notes_ko: '수도고속도로 위를 달리는 구간이 하이라이트. 도쿄에서 30분 거리.',
  },
  {
    id: 'kobe',
    name_ko: '고베 마라톤',
    name_en: 'Kobe Marathon',
    city_ko: '고베',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2026-11-15',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-04-01',
    entry_closes: '2026-05-07',
    entry_confidence: 'expected',
    entry_fee: 24200,
    entry_fee_currency: 'JPY',
    distances: ['풀'],
    field_size: 20000,
    course: '완만',
    flight_hours: 2.2,
    official_url: 'https://kobe-marathon.net/',
    source_url: 'https://japan-event.info/en/articles/japan-marathons-guide',
    last_verified: V,
    notes_ko: '한신·아와지 대지진 부흥 기념 대회. 응원 열기가 일본 최고 수준.',
  },
  {
    id: 'naha',
    name_ko: '나하 마라톤',
    name_en: 'NAHA Marathon',
    city_ko: '오키나와 나하',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2026-12-06',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-04-20',
    entry_closes: '2026-06-30',
    entry_confidence: 'expected',
    entry_fee: 11000,
    entry_fee_currency: 'JPY',
    distances: ['풀'],
    field_size: 30000,
    course: '언덕',
    flight_hours: 2.2,
    official_url: 'https://naha-marathon.jp/',
    source_url: 'https://japan-event.info/en/articles/japan-marathons-guide',
    last_verified: V,
    notes_ko: '참가비가 가장 싼 대형 대회. 12월인데도 20도 넘어 더위 대비 필수.',
  },
  {
    id: 'fuji',
    name_ko: '후지산 마라톤',
    name_en: 'Mt. Fuji Marathon',
    city_ko: '야마나시 가와구치코',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2026-12-13',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-04-15',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 15000,
    entry_fee_currency: 'JPY',
    distances: ['풀'],
    field_size: 3400,
    course: '언덕',
    flight_hours: 2.5,
    official_url: 'https://www.fujisan-marathon.jp/',
    source_url: 'https://www.fun-japan.jp/en/articles/14473',
    last_verified: V,
    notes_ko: '선착순이라 추첨 없이 확정 가능. 대신 코스 고저차가 커서 기록용은 아님.',
  },
  {
    id: 'kyoto',
    name_ko: '교토 마라톤',
    name_en: 'Kyoto Marathon',
    city_ko: '교토',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2027-02-21',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-08-01',
    entry_closes: '2026-09-30',
    entry_confidence: 'expected',
    entry_fee: 35000,
    entry_fee_currency: 'JPY',
    distances: ['풀'],
    field_size: 16000,
    course: '완만',
    flight_hours: 2.2,
    official_url: 'https://www.kyoto-marathon.com/',
    source_url: 'https://japan-event.info/en/articles/japan-marathons-guide',
    last_verified: V,
    notes_ko: '해외 참가자 슬롯 약 4,000석이 JTB 스포츠스테이션을 통해 별도 배정된다.',
  },
  {
    id: 'osaka',
    name_ko: '오사카 마라톤',
    name_en: 'Osaka Marathon',
    city_ko: '오사카',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2027-02-28',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-07-01',
    entry_closes: '2026-08-28',
    entry_confidence: 'confirmed',
    entry_fee: 21000,
    entry_fee_currency: 'JPY',
    distances: ['풀'],
    field_size: 32000,
    course: '평지',
    flight_hours: 2.0,
    official_url: 'https://www.osaka-marathon.com/',
    source_url: 'https://japan-event.info/en/articles/osaka-marathon-2027-entry',
    last_verified: V,
    notes_ko: '한국인 참가자가 가장 많은 해외 대회. 여행사 패키지 물량도 가장 크다.',
  },
  {
    id: 'tokyo',
    name_ko: '도쿄 마라톤',
    name_en: 'Tokyo Marathon',
    city_ko: '도쿄',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2027-03-07',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2026-08-14',
    entry_closes: '2026-08-28',
    entry_confidence: 'confirmed',
    entry_fee: 230,
    entry_fee_currency: 'USD',
    distances: ['풀'],
    field_size: 38000,
    course: '평지',
    flight_hours: 2.5,
    official_url: 'https://www.marathon.tokyo/en/',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '메이저 중 경쟁률 최상위(10:1 이상). 추첨 탈락 시 채리티/여행사 슬롯이 대안.',
  },
  {
    id: 'nagoya-women',
    name_ko: '나고야 우먼스 마라톤',
    name_en: "Nagoya Women's Marathon",
    city_ko: '나고야',
    country_ko: '일본',
    country_code: 'JP',
    region: '일본',
    race_date: '2027-03-14',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-09-01',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 16000,
    entry_fee_currency: 'JPY',
    distances: ['풀'],
    field_size: 22000,
    course: '평지',
    flight_hours: 1.8,
    official_url: 'https://womens-marathon.nagoya/en/',
    source_url: 'https://www.fun-japan.jp/en/articles/14473',
    last_verified: V,
    notes_ko: '여성 전용. 완주 시 티파니 펜던트를 준다. 해외 슬롯 약 3,500석 선착순.',
  },

  // ── 아시아 ────────────────────────────────────────────
  {
    id: 'taipei',
    name_ko: '타이베이 마라톤',
    name_en: 'Standard Chartered Taipei Marathon',
    city_ko: '타이베이',
    country_ko: '대만',
    country_code: 'TW',
    region: '아시아',
    race_date: '2027-01-10',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-08-01',
    entry_closes: '2026-08-31',
    entry_confidence: 'expected',
    entry_fee: 1600,
    entry_fee_currency: 'TWD',
    distances: ['풀', '하프'],
    field_size: 28000,
    course: '평지',
    flight_hours: 2.5,
    official_url: 'https://www.taipeicitymarathon.com/',
    source_url: 'https://www.runningkorea.com/',
    last_verified: V,
    notes_ko: '비행시간 짧고 물가 저렴해 첫 해외 마라톤으로 자주 추천된다.',
  },
  {
    id: 'hongkong',
    name_ko: '홍콩 마라톤',
    name_en: 'Standard Chartered Hong Kong Marathon',
    city_ko: '홍콩',
    country_ko: '홍콩',
    country_code: 'HK',
    region: '아시아',
    race_date: '2027-01-17',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-09-15',
    entry_closes: '2026-10-15',
    entry_confidence: 'tbc',
    entry_fee: 600,
    entry_fee_currency: 'HKD',
    distances: ['풀', '하프', '10km'],
    field_size: 74000,
    course: '언덕',
    flight_hours: 3.8,
    official_url: 'https://www.hkmarathon.com/',
    source_url: 'https://www.finishers.com/en/event/hong-kong-marathon',
    last_verified: V,
    notes_ko: '해저터널·대교 구간이 있어 오르내림이 많다. 새벽 출발.',
  },
  {
    id: 'singapore',
    name_ko: '싱가포르 마라톤',
    name_en: 'Standard Chartered Singapore Marathon',
    city_ko: '싱가포르',
    country_ko: '싱가포르',
    country_code: 'SG',
    region: '아시아',
    race_date: '2026-12-06',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-05-01',
    entry_closes: '2026-11-15',
    entry_confidence: 'expected',
    entry_fee: 138,
    entry_fee_currency: 'SGD',
    distances: ['풀', '하프', '10km'],
    field_size: 50000,
    course: '평지',
    flight_hours: 6.5,
    official_url: 'https://www.singaporemarathon.com/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '고온다습. 야간/새벽 출발이라 기록보다 완주 목표로 접근하는 편이 낫다.',
  },
  {
    id: 'angkor',
    name_ko: '앙코르와트 국제 하프마라톤',
    name_en: 'Angkor Wat International Half Marathon',
    city_ko: '시엠립',
    country_ko: '캄보디아',
    country_code: 'KH',
    region: '아시아',
    race_date: '2026-12-06',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-06-01',
    entry_closes: '2026-11-20',
    entry_confidence: 'expected',
    entry_fee: 60,
    entry_fee_currency: 'USD',
    distances: ['하프', '10km', '5km'],
    field_size: 12000,
    course: '평지',
    flight_hours: 5.5,
    official_url: 'https://www.angkormarathon.org/',
    source_url: null,
    last_verified: V,
    notes_ko: '유적지 사이를 달리는 관광형 대회. 풀코스는 없고 하프가 최장.',
  },
  {
    id: 'mumbai',
    name_ko: '뭄바이 마라톤',
    name_en: 'Tata Mumbai Marathon',
    city_ko: '뭄바이',
    country_ko: '인도',
    country_code: 'IN',
    region: '아시아',
    race_date: '2027-01-17',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-11-01',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 100,
    entry_fee_currency: 'USD',
    distances: ['풀', '하프', '10km'],
    field_size: 55000,
    course: '완만',
    flight_hours: 9.5,
    official_url: 'https://procam.in/event/tata-mumbai-marathon/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '직항이 없어 경유 필요. 아시아 최대 규모 중 하나.',
  },
  {
    id: 'shanghai',
    name_ko: '상하이 마라톤',
    name_en: 'Shanghai Marathon',
    city_ko: '상하이',
    country_ko: '중국',
    country_code: 'CN',
    region: '아시아',
    race_date: '2026-12-06',
    date_confidence: 'expected',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2026-09-01',
    entry_closes: '2026-09-20',
    entry_confidence: 'tbc',
    entry_fee: 200,
    entry_fee_currency: 'CNY',
    distances: ['풀'],
    field_size: 38000,
    course: '평지',
    flight_hours: 2.0,
    official_url: 'https://www.shmarathon.com/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '2025년 월드 마라톤 메이저스에 합류. 비행 2시간으로 메이저 중 가장 가깝다.',
  },

  // ── 오세아니아 ────────────────────────────────────────
  {
    id: 'sydney',
    name_ko: '시드니 마라톤',
    name_en: 'TCS Sydney Marathon',
    city_ko: '시드니',
    country_ko: '호주',
    country_code: 'AU',
    region: '오세아니아',
    race_date: '2027-08-29',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2026-09-28',
    entry_closes: '2026-10-16',
    entry_confidence: 'expected',
    entry_fee: 330,
    entry_fee_currency: 'AUD',
    distances: ['풀'],
    field_size: 35000,
    course: '언덕',
    flight_hours: 10.5,
    official_url: 'https://www.sydneymarathon.org/',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '2025년 메이저 승격. 하버브리지와 오페라하우스 피니시. 신설 메이저라 아직 경쟁률이 낮은 편.',
  },
  {
    id: 'goldcoast',
    name_ko: '골드코스트 마라톤',
    name_en: 'ASICS Gold Coast Marathon',
    city_ko: '골드코스트',
    country_ko: '호주',
    country_code: 'AU',
    region: '오세아니아',
    race_date: '2027-07-04',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-09-01',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 220,
    entry_fee_currency: 'AUD',
    distances: ['풀', '하프', '10km'],
    field_size: 27000,
    course: '평지',
    flight_hours: 10.0,
    official_url: 'https://goldcoastmarathon.com.au/',
    source_url: 'https://marathonscout.com/races/gold-coast-marathon',
    last_verified: V,
    notes_ko: '완전 평지 + 서늘한 겨울 날씨로 개인 최고기록 도전용으로 유명. 선착순이지만 조기 마감된다.',
  },

  // ── 유럽 ──────────────────────────────────────────────
  {
    id: 'amsterdam',
    name_ko: '암스테르담 마라톤',
    name_en: 'TCS Amsterdam Marathon',
    city_ko: '암스테르담',
    country_ko: '네덜란드',
    country_code: 'NL',
    region: '유럽',
    race_date: '2026-10-18',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2025-12-01',
    entry_closes: '2026-09-30',
    entry_confidence: 'expected',
    entry_fee: 110,
    entry_fee_currency: 'EUR',
    distances: ['풀', '하프', '8km'],
    field_size: 20000,
    course: '평지',
    flight_hours: 11.5,
    official_url: 'https://www.tcsamsterdammarathon.nl/en/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '올림픽 스타디움 출발·도착. 유럽 평지 코스 중 손꼽히는 기록 코스.',
  },
  {
    id: 'dublin',
    name_ko: '더블린 마라톤',
    name_en: 'Irish Life Dublin Marathon',
    city_ko: '더블린',
    country_ko: '아일랜드',
    country_code: 'IE',
    region: '유럽',
    race_date: '2026-10-25',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2025-11-01',
    entry_closes: '2025-11-30',
    entry_confidence: 'expected',
    entry_fee: 115,
    entry_fee_currency: 'EUR',
    distances: ['풀'],
    field_size: 22500,
    course: '완만',
    flight_hours: 14.0,
    official_url: 'https://www.irishlifedublinmarathon.ie/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '추첨제로 전환된 뒤 경쟁률이 올랐다. 직항이 없어 경유 필요.',
  },
  {
    id: 'athens',
    name_ko: '아테네 마라톤',
    name_en: 'Athens Authentic Marathon',
    city_ko: '아테네',
    country_ko: '그리스',
    country_code: 'GR',
    region: '유럽',
    race_date: '2026-11-08',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-04-01',
    entry_closes: '2026-10-10',
    entry_confidence: 'expected',
    entry_fee: 95,
    entry_fee_currency: 'EUR',
    distances: ['풀', '10km', '5km'],
    field_size: 20000,
    course: '언덕',
    flight_hours: 14.0,
    official_url: 'https://www.athensauthenticmarathon.gr/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '마라톤 발상지 코스. 20~31km 구간이 계속 오르막이라 난이도가 높다.',
  },
  {
    id: 'valencia',
    name_ko: '발렌시아 마라톤',
    name_en: 'Valencia Marathon',
    city_ko: '발렌시아',
    country_ko: '스페인',
    country_code: 'ES',
    region: '유럽',
    race_date: '2026-12-06',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'lottery',
    entry_opens: '2026-01-15',
    entry_closes: '2026-02-15',
    entry_confidence: 'expected',
    entry_fee: 105,
    entry_fee_currency: 'EUR',
    distances: ['풀'],
    field_size: 35000,
    course: '평지',
    flight_hours: 15.0,
    official_url: 'https://www.valenciaciudaddelrunning.com/en/marathon/',
    source_url: 'https://therunningchannel.com/valencia-marathon-ballot-2026/',
    last_verified: V,
    notes_ko: '2026년부터 추첨제 도입. 세계에서 가장 빠른 코스로 평가받는다.',
  },
  {
    id: 'seville',
    name_ko: '세비야 마라톤',
    name_en: 'Zurich Maratón de Sevilla',
    city_ko: '세비야',
    country_ko: '스페인',
    country_code: 'ES',
    region: '유럽',
    race_date: '2027-02-21',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-04-01',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 85,
    entry_fee_currency: 'EUR',
    distances: ['풀'],
    field_size: 14000,
    course: '평지',
    flight_hours: 16.0,
    official_url: 'https://www.zurichmaratonsevilla.es/en/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '유럽에서 가장 평평한 코스로 꼽힌다. 2월이라 기온도 러닝에 적합.',
  },
  {
    id: 'rome',
    name_ko: '로마 마라톤',
    name_en: 'Acea Run Rome The Marathon',
    city_ko: '로마',
    country_ko: '이탈리아',
    country_code: 'IT',
    region: '유럽',
    race_date: '2027-03-14',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-04-01',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 110,
    entry_fee_currency: 'EUR',
    distances: ['풀'],
    field_size: 20000,
    course: '완만',
    flight_hours: 12.5,
    official_url: 'https://www.runromethemarathon.com/en/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '콜로세움 출발·도착. 돌바닥(sampietrini) 구간이 있어 신발 선택이 중요하다.',
  },
  {
    id: 'paris',
    name_ko: '파리 마라톤',
    name_en: 'Schneider Electric Marathon de Paris',
    city_ko: '파리',
    country_ko: '프랑스',
    country_code: 'FR',
    region: '유럽',
    race_date: '2027-04-11',
    date_confidence: 'tbc',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-04-15',
    entry_closes: null,
    entry_confidence: 'tbc',
    entry_fee: 135,
    entry_fee_currency: 'EUR',
    distances: ['풀'],
    field_size: 54000,
    course: '완만',
    flight_hours: 12.5,
    official_url: 'https://www.schneiderelectricparismarathon.com/en',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '메이저는 아니지만 규모는 메이저급. 선착순이라 오픈 직후 신청하면 확정된다.',
  },
  {
    id: 'manchester',
    name_ko: '맨체스터 마라톤',
    name_en: 'adidas Manchester Marathon',
    city_ko: '맨체스터',
    country_ko: '영국',
    country_code: 'GB',
    region: '유럽',
    race_date: '2027-04-18',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-04-20',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 75,
    entry_fee_currency: 'GBP',
    distances: ['풀'],
    field_size: 30000,
    course: '평지',
    flight_hours: 14.0,
    official_url: 'https://www.manchestermarathon.co.uk/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '런던 추첨 탈락자들이 몰리는 대안. 영국에서 가장 평평한 대형 코스.',
  },
  {
    id: 'london',
    name_ko: '런던 마라톤',
    name_en: 'TCS London Marathon',
    city_ko: '런던',
    country_ko: '영국',
    country_code: 'GB',
    region: '유럽',
    race_date: '2027-04-25',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2026-04-24',
    entry_closes: '2026-05-01',
    entry_confidence: 'confirmed',
    entry_fee: 80,
    entry_fee_currency: 'GBP',
    distances: ['풀'],
    field_size: 56000,
    course: '평지',
    flight_hours: 12.0,
    official_url: 'https://www.tcslondonmarathon.com/',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '세계 최대 규모. 2027년 대회 추첨은 2026년 5월에 이미 종료 — 다음 기회는 2028년 대회 응모.',
  },
  {
    id: 'berlin',
    name_ko: '베를린 마라톤',
    name_en: 'BMW Berlin Marathon',
    city_ko: '베를린',
    country_ko: '독일',
    country_code: 'DE',
    region: '유럽',
    race_date: '2027-09-26',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2026-09-25',
    entry_closes: '2026-11-06',
    entry_confidence: 'expected',
    entry_fee: 205,
    entry_fee_currency: 'EUR',
    distances: ['풀'],
    field_size: 55000,
    course: '평지',
    flight_hours: 11.5,
    official_url: 'https://www.bmw-berlin-marathon.com/en/',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '세계기록이 가장 많이 나온 코스. 추첨 외에 기록 기준 확정 엔트리(서브3 등)도 있다.',
  },

  // ── 북미 ──────────────────────────────────────────────
  {
    id: 'honolulu',
    name_ko: '호놀룰루 마라톤',
    name_en: 'Honolulu Marathon',
    city_ko: '호놀룰루',
    country_ko: '미국',
    country_code: 'US',
    region: '북미',
    race_date: '2026-12-13',
    date_confidence: 'confirmed',
    is_major: false,
    entry_type: 'open',
    entry_opens: '2026-01-01',
    entry_closes: '2026-12-11',
    entry_confidence: 'expected',
    entry_fee: 265,
    entry_fee_currency: 'USD',
    distances: ['풀', '10km'],
    field_size: 25000,
    course: '완만',
    flight_hours: 8.0,
    official_url: 'https://www.honolulumarathon.org/',
    source_url: null,
    last_verified: V,
    notes_ko: '인원 제한도 제한시간도 없다. 추첨 걱정 없이 확정 참가 가능한 대표 대회.',
  },
  {
    id: 'la',
    name_ko: 'LA 마라톤',
    name_en: 'McDonald’s LA Marathon',
    city_ko: '로스앤젤레스',
    country_ko: '미국',
    country_code: 'US',
    region: '북미',
    race_date: '2027-03-07',
    date_confidence: 'expected',
    is_major: false,
    entry_type: 'fcfs',
    entry_opens: '2026-03-15',
    entry_closes: null,
    entry_confidence: 'expected',
    entry_fee: 200,
    entry_fee_currency: 'USD',
    distances: ['풀'],
    field_size: 25000,
    course: '완만',
    flight_hours: 11.0,
    official_url: 'https://www.lamarathon.com/',
    source_url: 'https://bibsalert.com/races/marathon-calendar',
    last_verified: V,
    notes_ko: '정원 찰 때까지 상시 접수. 미국 메이저 추첨 탈락 시 대안으로 자주 선택된다.',
  },
  {
    id: 'boston',
    name_ko: '보스턴 마라톤',
    name_en: 'Boston Marathon',
    city_ko: '보스턴',
    country_ko: '미국',
    country_code: 'US',
    region: '북미',
    race_date: '2027-04-19',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'qualifying',
    entry_opens: '2026-09-07',
    entry_closes: '2026-09-11',
    entry_confidence: 'expected',
    entry_fee: 260,
    entry_fee_currency: 'USD',
    distances: ['풀'],
    field_size: 30000,
    course: '언덕',
    flight_hours: 14.0,
    official_url: 'https://www.baa.org/',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '유일하게 추첨이 없는 메이저. 연령대별 기준기록 충족 + 실제로는 기준보다 수 분 빨라야 통과된다.',
  },
  {
    id: 'chicago',
    name_ko: '시카고 마라톤',
    name_en: 'Bank of America Chicago Marathon',
    city_ko: '시카고',
    country_ko: '미국',
    country_code: 'US',
    region: '북미',
    race_date: '2027-10-10',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2026-10-21',
    entry_closes: '2026-11-18',
    entry_confidence: 'expected',
    entry_fee: 260,
    entry_fee_currency: 'USD',
    distances: ['풀'],
    field_size: 52000,
    course: '평지',
    flight_hours: 13.0,
    official_url: 'https://www.chicagomarathon.com/',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '메이저 중 평지 코스라 기록 노리기 좋다. 기록 기준 확정 엔트리도 별도로 있다.',
  },
  {
    id: 'nyc',
    name_ko: '뉴욕 마라톤',
    name_en: 'TCS New York City Marathon',
    city_ko: '뉴욕',
    country_ko: '미국',
    country_code: 'US',
    region: '북미',
    race_date: '2027-11-07',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2027-02-04',
    entry_closes: '2027-02-25',
    entry_confidence: 'expected',
    entry_fee: 315,
    entry_fee_currency: 'USD',
    distances: ['풀'],
    field_size: 55000,
    course: '언덕',
    flight_hours: 14.0,
    official_url: 'https://www.nyrr.org/tcsnycmarathon',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '다리 5개를 건너는 코스라 오르내림이 많다. 응모료(약 $12)가 따로 있다.',
  },

  // ── 기타 ──────────────────────────────────────────────
  {
    id: 'capetown',
    name_ko: '케이프타운 마라톤',
    name_en: 'Cape Town Marathon',
    city_ko: '케이프타운',
    country_ko: '남아프리카공화국',
    country_code: 'ZA',
    region: '기타',
    race_date: '2027-05-23',
    date_confidence: 'confirmed',
    is_major: true,
    entry_type: 'lottery',
    entry_opens: '2026-06-10',
    entry_closes: '2026-06-24',
    entry_confidence: 'confirmed',
    entry_fee: 2200,
    entry_fee_currency: 'ZAR',
    distances: ['풀'],
    field_size: 22000,
    course: '완만',
    flight_hours: 20.0,
    official_url: 'https://www.capetownmarathon.com/',
    source_url: 'https://runwitholivia.com/resources/world-marathon-majors-2027-ballot-dates',
    last_verified: V,
    notes_ko: '2025년 메이저 승격. 이동이 가장 길지만 메이저 중 추첨 경쟁률은 낮은 편.',
  },
];

export const AGENCIES: Agency[] = [
  { id: 'runningkorea', name: '러닝코리아', url: 'https://www.runningkorea.com/', note: '해외마라톤 전문. 상품 수가 가장 많다.' },
  { id: 'okentry', name: '오케이엔트리', url: 'https://www.okentry.com/', note: '메이저 대회 위주. 엔트리 대행도 취급.' },
  { id: 'opencaretour', name: '오픈케어스포츠투어', url: 'https://www.opencaretour.com/', note: '6대 메이저 중심 패키지.' },
  { id: 'snbtour', name: 'SNB투어', url: 'https://www.snbtour.com/', note: '일본 대회(오사카·도쿄) 물량이 많다.' },
  { id: 'lottejtb', name: '롯데JTB 런트립', url: 'https://www.lottejtb.com/', note: '일본 대회 공식 슬롯 연계.' },
  { id: 'marathontours', name: 'Marathon Tours & Travel', url: 'https://marathontours.com/', note: '해외 업체. 메이저 공식 투어 오퍼레이터.' },
];

/**
 * 여행사 패키지.
 * price_* 가 null 이면 UI 에서 "가격 문의"로 표시하고 링크만 건다.
 * 확인된 가격은 러닝코리아 공개 상품가(2026-08 기준) 기준.
 */
export const PACKAGES: Package[] = [
  {
    id: 'rk-taipei',
    race_id: 'taipei',
    agency_id: 'runningkorea',
    title: 'SC 타이베이 마라톤 4일',
    nights: 3,
    price_solo_krw: 1250000,
    price_group_krw: null,
    group_min: null,
    includes: ['항공', '호텔', '조식', '인솔자', '여행자보험'],
    url: 'https://www.runningkorea.com/',
    updated_at: V,
  },
  {
    id: 'rk-nagoya',
    race_id: 'nagoya-women',
    agency_id: 'runningkorea',
    title: '나고야 우먼스 마라톤 4일',
    nights: 3,
    price_solo_krw: 1350000,
    price_group_krw: null,
    group_min: null,
    includes: ['항공', '호텔', '조식', '인솔자', '여행자보험'],
    url: 'https://www.runningkorea.com/',
    updated_at: V,
  },
  {
    id: 'rk-boston',
    race_id: 'boston',
    agency_id: 'runningkorea',
    title: '보스턴 마라톤 8일',
    nights: 7,
    price_solo_krw: 4850000,
    price_group_krw: null,
    group_min: null,
    includes: ['항공', '호텔', '조식', '인솔자', '여행자보험'],
    url: 'https://www.runningkorea.com/',
    updated_at: V,
  },
  {
    id: 'rk-capetown',
    race_id: 'capetown',
    agency_id: 'runningkorea',
    title: '케이프타운 마라톤 7일',
    nights: 6,
    price_solo_krw: 4850000,
    price_group_krw: null,
    group_min: null,
    includes: ['항공', '호텔', '조식', '인솔자', '여행자보험'],
    url: 'https://www.runningkorea.com/',
    updated_at: V,
  },
  {
    id: 'rk-osaka',
    race_id: 'osaka',
    agency_id: 'runningkorea',
    title: '오사카 마라톤 4일 (A/B팀)',
    nights: 3,
    price_solo_krw: null,
    price_group_krw: null,
    group_min: null,
    includes: ['항공', '호텔', '조식', '일부식사', '인솔자', '여행자보험', '유류할증료'],
    url: 'https://www.runningkorea.com/',
    updated_at: V,
  },
  { id: 'snb-osaka', race_id: 'osaka', agency_id: 'snbtour', title: '오사카 마라톤 패키지', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['항공', '호텔', '엔트리'], url: 'https://www.snbtour.com/', updated_at: V },
  { id: 'jtb-osaka', race_id: 'osaka', agency_id: 'lottejtb', title: '[런트립x일본] 오사카 마라톤', nights: 2, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['항공', '호텔', '엔트리'], url: 'https://www.lottejtb.com/', updated_at: V },
  { id: 'ok-osaka', race_id: 'osaka', agency_id: 'okentry', title: '오사카 마라톤 (이달의 추천)', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['엔트리 대행'], url: 'https://www.okentry.com/', updated_at: V },
  { id: 'ok-boston', race_id: 'boston', agency_id: 'okentry', title: '보스턴 마라톤 (이달의 추천)', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['엔트리 대행'], url: 'https://www.okentry.com/', updated_at: V },
  { id: 'ok-london', race_id: 'london', agency_id: 'okentry', title: 'TCS 런던 마라톤 (이달의 추천)', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['엔트리 대행'], url: 'https://www.okentry.com/', updated_at: V },
  { id: 'ok-capetown', race_id: 'capetown', agency_id: 'okentry', title: '케이프타운 마라톤 (이달의 추천)', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['엔트리 대행'], url: 'https://www.okentry.com/', updated_at: V },
  { id: 'oc-tokyo', race_id: 'tokyo', agency_id: 'opencaretour', title: '도쿄 마라톤 메이저 패키지', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['항공', '호텔', '엔트리'], url: 'https://www.opencaretour.com/', updated_at: V },
  { id: 'oc-berlin', race_id: 'berlin', agency_id: 'opencaretour', title: '베를린 마라톤 메이저 패키지', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['항공', '호텔', '엔트리'], url: 'https://www.opencaretour.com/', updated_at: V },
  { id: 'mt-goldcoast', race_id: 'goldcoast', agency_id: 'marathontours', title: 'Gold Coast Marathon Official Tour', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['Guaranteed entry', 'Hotel'], url: 'https://marathontours.com/en-au/events/gold-coast-marathon/', updated_at: V },
  { id: 'mt-tokyo', race_id: 'tokyo', agency_id: 'marathontours', title: 'Tokyo Marathon Official Tour (보장 엔트리)', nights: null, price_solo_krw: null, price_group_krw: null, group_min: null, includes: ['Guaranteed entry', 'Hotel'], url: 'https://marathontours.com/', updated_at: V },
];

/** 인천 출발 기준 왕복 항공 + 1박 숙박 + 1일 체류비 추정치 (KRW, 2026-08 기준 참고용) */
export const COSTS: CostBaseline[] = [
  { race_id: 'JP', flight_low_krw: 250000, flight_mid_krw: 420000, flight_high_krw: 700000, hotel_night_krw: 140000, daily_krw: 80000 },
  { race_id: 'TW', flight_low_krw: 300000, flight_mid_krw: 480000, flight_high_krw: 780000, hotel_night_krw: 120000, daily_krw: 60000 },
  { race_id: 'HK', flight_low_krw: 350000, flight_mid_krw: 550000, flight_high_krw: 900000, hotel_night_krw: 200000, daily_krw: 90000 },
  { race_id: 'CN', flight_low_krw: 250000, flight_mid_krw: 400000, flight_high_krw: 650000, hotel_night_krw: 130000, daily_krw: 70000 },
  { race_id: 'SG', flight_low_krw: 450000, flight_mid_krw: 700000, flight_high_krw: 1100000, hotel_night_krw: 220000, daily_krw: 100000 },
  { race_id: 'KH', flight_low_krw: 400000, flight_mid_krw: 620000, flight_high_krw: 950000, hotel_night_krw: 90000, daily_krw: 50000 },
  { race_id: 'IN', flight_low_krw: 700000, flight_mid_krw: 1000000, flight_high_krw: 1500000, hotel_night_krw: 110000, daily_krw: 50000 },
  { race_id: 'AU', flight_low_krw: 900000, flight_mid_krw: 1350000, flight_high_krw: 2000000, hotel_night_krw: 210000, daily_krw: 110000 },
  { race_id: 'US', flight_low_krw: 1200000, flight_mid_krw: 1800000, flight_high_krw: 2800000, hotel_night_krw: 260000, daily_krw: 120000 },
  { race_id: 'GB', flight_low_krw: 1100000, flight_mid_krw: 1650000, flight_high_krw: 2500000, hotel_night_krw: 240000, daily_krw: 110000 },
  { race_id: 'DE', flight_low_krw: 1050000, flight_mid_krw: 1600000, flight_high_krw: 2400000, hotel_night_krw: 200000, daily_krw: 100000 },
  { race_id: 'NL', flight_low_krw: 1050000, flight_mid_krw: 1600000, flight_high_krw: 2400000, hotel_night_krw: 220000, daily_krw: 105000 },
  { race_id: 'FR', flight_low_krw: 1100000, flight_mid_krw: 1650000, flight_high_krw: 2500000, hotel_night_krw: 230000, daily_krw: 110000 },
  { race_id: 'IT', flight_low_krw: 1050000, flight_mid_krw: 1600000, flight_high_krw: 2400000, hotel_night_krw: 190000, daily_krw: 100000 },
  { race_id: 'ES', flight_low_krw: 1100000, flight_mid_krw: 1700000, flight_high_krw: 2600000, hotel_night_krw: 170000, daily_krw: 90000 },
  { race_id: 'IE', flight_low_krw: 1200000, flight_mid_krw: 1750000, flight_high_krw: 2600000, hotel_night_krw: 230000, daily_krw: 110000 },
  { race_id: 'GR', flight_low_krw: 1100000, flight_mid_krw: 1650000, flight_high_krw: 2500000, hotel_night_krw: 160000, daily_krw: 85000 },
  { race_id: 'ZA', flight_low_krw: 1600000, flight_mid_krw: 2200000, flight_high_krw: 3200000, hotel_night_krw: 150000, daily_krw: 80000 },
];

/** 참가비 환산용 대략 환율 (KRW, 2026-08 기준 참고용) */
export const FX: Record<string, number> = {
  KRW: 1,
  USD: 1380,
  JPY: 9.2,
  EUR: 1500,
  GBP: 1760,
  AUD: 900,
  SGD: 1030,
  HKD: 177,
  TWD: 43,
  CNY: 192,
  ZAR: 76,
  INR: 16,
};
